sudo: false

language: node_js

node_js:
  - 7.7

before_install:
  - gem install compass
  - npm install -g grunt-cli bower

install:
  - npm install
  - bower install

script:
  - grunt build

before_deploy:
  - mv dist "pj-app-${TRAVIS_TAG}"
  - tar -caf "pj-app-${TRAVIS_TAG}.tar.xz" "pj-app-${TRAVIS_TAG}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: e92CqIzgCjJV4Vfa7TD98caqEsScg0mcJSPn5zUsr261yEUeIhpJLJHjza32JICw0AVXc1HAhqO9HucUIREFcEvI3whSMx4xkaV52X4QKh1KC0E980TS2sLbNCQqjGxT6rJe+l6NggPKQuteasTdJ/f2k7D6RtK2SUlDl2HFcC0=
  file: "pj-app-${TRAVIS_TAG}.tar.xz"
  on:
    repo: ushis/pj-app
    tags: true
